version: "3"
services:

 mongo:
  image: mongo:5.0.3
  container_name: mongo
  ports:
   - "27017:27017"
  environment:
      - REDIS_CACHE_TIMEOUT=3600
  volumes:
   - mongo-data:/data/db
  
 service-registry:
  build:
   context: ./diploma-service-registry
  container_name: service-registry
  ports:
   - "8761:8761"
  depends_on:
   - mongo

 api-gateway:
  build:
   context: ./diploma-api-gateway
  container_name: api
  environment:
   - REGISTRY_HOST=service-registry
   - REGISTRY_PORT=8761
   - REDIS_CACHE_TIMEOUT=3600
  ports:
   - "8080:8080"
  depends_on:
   - mongo


 dictionary-parser:
  build:
   context: ./diploma-dictionary
  container_name: dictionary-parser
  environment:
   - SPRING_DATA_MONGODB_HOST=mongo
   - SPRING_DATA_MONGODB_PORT=27017

   - REGISTRY_HOST=service-registry
   - REGISTRY_PORT=8761
   
   - REDIS_CACHE_TIMEOUT=3600
  ports:
   - "1111:1111"
  depends_on:
   - mongo

 client:
  build:
   context: ./diploma-client/dockerimage
  container_name: client
  ports:
   - "5953:80"
   - "443:443"

volumes:
 mongo-data:
 rabbitmq-data:

